// Tests for app/analysis.{h,cpp} — chord counting cross-checked against
// golden's `song` block (same tally, computed a different way), plus
// discovery/hashing sanity over the real test/input corpus (not gated by
// golden: these are filesystem-facing, not part of the algorithm spine).

#include "doctest.h"

#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>

#include <cstdio>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "app/analysis.h"
#include "golden_util.h"
#include "store/record_store.h"

using namespace hydra::app;

namespace {

// Chart libraries routinely have non-ASCII paths (this corpus has one with a
// fullwidth slash); std::ifstream's narrow-string overload goes through the
// system codepage on Windows and mangles those, so round-trip through UTF-16
// like analysis.cpp's own file reads do.
bool file_exists_utf8(const std::string& utf8_path) {
    int wlen =
        MultiByteToWideChar(CP_UTF8, 0, utf8_path.data(), (int)utf8_path.size(), nullptr, 0);
    std::wstring wpath((size_t)wlen, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, utf8_path.data(), (int)utf8_path.size(), &wpath[0], wlen);
    FILE* f = _wfopen(wpath.c_str(), L"rb");
    if (!f) return false;
    std::fclose(f);
    return true;
}

}  // namespace

TEST_CASE("count_chart_chords matches golden's song-block code tally") {
    const golden::json idx = golden::index();
    int checked = 0;

    for (const auto& entry : idx) {
        const std::string relpath = entry["relpath"].get<std::string>();
        const std::string ext = relpath.substr(relpath.find_last_of('.') + 1);
        if (ext != "mid" && ext != "chart") continue;  // count_chart_chords doesn't take .sng

        golden::json doc = golden::chart(entry["slug"].get<std::string>());
        std::map<std::string, int> expected;
        for (const auto& ev : doc["song"]["events"]) ++expected[ev["code"].get<std::string>()];

        const std::string path = std::string(HYDRA_INPUT_DIR) + "/" + relpath;
        std::map<std::string, int> actual = count_chart_chords(path);

        CHECK_MESSAGE(actual == expected, relpath);
        ++checked;
    }

    CHECK(checked > 0);
    MESSAGE("checked " << checked << " charts");
}

TEST_CASE("discover_charts walks the corpus without throwing") {
    auto [items, errors] = discover_charts({std::string(HYDRA_INPUT_DIR)});
    CHECK(errors.empty());

    for (const ScanItem& item : items) {
        CHECK_MESSAGE(file_exists_utf8(item.notespath), item.notespath);
        CHECK(item.md5.size() == 32);
        for (char c : item.md5)
            CHECK((std::isxdigit(static_cast<unsigned char>(c)) != 0));
    }

    MESSAGE("discovered " << items.size() << " chart(s)");
}

TEST_CASE("discover_charts returns nothing for an empty root list") {
    auto [items, errors] = discover_charts({});
    CHECK(items.empty());
    CHECK(errors.empty());
}

TEST_CASE("get_folder_count agrees with the folder count discover_charts visits") {
    int seen_by_discover = 0;
    discover_charts({std::string(HYDRA_INPUT_DIR)},
                    [&](int n) { seen_by_discover = n; });
    int counted = get_folder_count({std::string(HYDRA_INPUT_DIR)});
    CHECK(counted == seen_by_discover);
}

namespace {

// notespath/rootfolder relative to test/input, forward slashes — the keying
// test/scan_snapshot.json uses (see tools/bench.cpp's --dump-rel).
std::string rel_of(const std::string& path, const std::string& root) {
    std::string rel = path;
    if (!root.empty() && rel.size() > root.size() && rel.compare(0, root.size(), root) == 0)
        rel = rel.substr(root.size() + 1);
    for (char& c : rel)
        if (c == '\\') c = '/';
    return rel;
}

}  // namespace

// The fixture was generated by the pre-rework serial scanner (whole-file MD5,
// separate metadata reads), so this pins the digests, metadata, and discovery
// set across any scan implementation change.
TEST_CASE("discover_charts output matches the checked-in scan snapshot") {
    const std::string input = HYDRA_INPUT_DIR;
    std::ifstream f(input + "/../scan_snapshot.json", std::ios::binary);
    REQUIRE_MESSAGE(bool(f), "missing test/scan_snapshot.json");
    std::stringstream ss;
    ss << f.rdbuf();
    golden::json snapshot = golden::json::parse(ss.str());

    auto [items, errors] = discover_charts({input});
    CHECK(errors.empty());
    CHECK(items.size() == snapshot.size());

    std::map<std::string, const ScanItem*> by_rel;
    for (const ScanItem& item : items) by_rel[rel_of(item.notespath, input)] = &item;

    for (const auto& row : snapshot) {
        const std::string rel = row["path"].get<std::string>();
        auto it = by_rel.find(rel);
        REQUIRE_MESSAGE(it != by_rel.end(), "not discovered: " << rel);
        const ScanItem& item = *it->second;
        CHECK_MESSAGE(item.md5 == row["md5"].get<std::string>(), rel);
        CHECK_MESSAGE(item.title == row["title"].get<std::string>(), rel);
        CHECK_MESSAGE(item.artist == row["artist"].get<std::string>(), rel);
        CHECK_MESSAGE(item.charter == row["charter"].get<std::string>(), rel);
        CHECK_MESSAGE(rel_of(item.rootfolder, "") == row["folder"].get<std::string>(), rel);
    }
}

TEST_CASE("rescan cache reproduces the scan without reading chart files") {
    const std::string input = HYDRA_INPUT_DIR;
    auto [items, errors] = discover_charts({input});
    REQUIRE(errors.empty());
    REQUIRE(!items.empty());

    hydra::store::RecordStore store(":memory:", false);
    std::vector<hydra::store::ChartLibraryEntry> entries;
    for (const ScanItem& it : items)
        entries.push_back({it.md5, it.title, it.artist, it.charter, it.notespath,
                           it.rootfolder, it.sig});
    store.rebuild_chart_library(entries);

    hydra::store::ChartLibraryCache cache = store.chart_library_cache();
    CHECK(cache.size() == items.size());

    int last_cached = 0, last_done = 0;
    ScanCallbacks callbacks;
    callbacks.on_charts = [&](int done, int, int cached) {
        last_done = done;
        last_cached = cached;
    };
    auto [items2, errors2] = discover_charts({input}, callbacks, &cache);
    CHECK(errors2.empty());

    // Every chart came out of the cache (no file was opened for content)...
    CHECK(last_done == static_cast<int>(items.size()));
    CHECK(last_cached == static_cast<int>(items.size()));

    // ...and the results are identical, field for field, in the same order.
    REQUIRE(items2.size() == items.size());
    for (size_t i = 0; i < items.size(); ++i) {
        CHECK(items2[i].md5 == items[i].md5);
        CHECK(items2[i].title == items[i].title);
        CHECK(items2[i].artist == items[i].artist);
        CHECK(items2[i].charter == items[i].charter);
        CHECK(items2[i].notespath == items[i].notespath);
        CHECK(items2[i].rootfolder == items[i].rootfolder);
        CHECK(items2[i].sig == items[i].sig);
    }
}
