// Tests for app/analysis.{h,cpp}: discovery/hashing sanity over the real
// testdata/input corpus.

#include "doctest.h"

#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>

#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "app/analysis.h"
#include "core/winstr.h"
#include "corpus_util.h"
#include "midi_util.h"
#include "parse/song.h"
#include "store/record_store.h"

#ifndef HYDRA_TESTDATA_DIR
#error "HYDRA_TESTDATA_DIR must be defined (see CMakeLists.txt)"
#endif

using namespace hydra::app;

using hydra::file_exists_utf8;

TEST_CASE("discover_charts walks the corpus without throwing") {
    auto [items, errors] = discover_charts({std::string(HYDRA_INPUT_DIR)});
    CHECK(errors.empty());

    for (const ScanItem& item : items) {
        CHECK_MESSAGE(file_exists_utf8(item.notespath), item.notespath);
        CHECK(item.md5.size() == 32);
        for (char c : item.md5)
            CHECK((std::isxdigit(static_cast<unsigned char>(c)) != 0));
    }

    MESSAGE("discovered " << items.size() << " chart(s)");
}

TEST_CASE("discover_charts returns nothing for an empty root list") {
    auto [items, errors] = discover_charts({});
    CHECK(items.empty());
    CHECK(errors.empty());
}

namespace {

// notespath/rootfolder relative to testdata/input, forward slashes — the
// keying testdata/scan_snapshot.json uses (see tools/bench.cpp's --dump-rel).
std::string rel_of(const std::string& path, const std::string& root) {
    std::string rel = path;
    if (!root.empty() && rel.size() > root.size() && rel.compare(0, root.size(), root) == 0)
        rel = rel.substr(root.size() + 1);
    for (char& c : rel)
        if (c == '\\') c = '/';
    return rel;
}

}  // namespace

// The fixture was generated by the pre-rework serial scanner (whole-file MD5,
// separate metadata reads), so this pins the digests, metadata, and discovery
// set across any scan implementation change.
TEST_CASE("discover_charts output matches the checked-in scan snapshot") {
    const std::string input = HYDRA_INPUT_DIR;
    std::ifstream f(std::string(HYDRA_TESTDATA_DIR) + "/scan_snapshot.json",
                    std::ios::binary);
    REQUIRE_MESSAGE(bool(f), "missing testdata/scan_snapshot.json");
    std::stringstream ss;
    ss << f.rdbuf();
    corpus::json snapshot = corpus::json::parse(ss.str());

    auto [items, errors] = discover_charts({input});
    CHECK(errors.empty());
    CHECK(items.size() == snapshot.size());

    std::map<std::string, const ScanItem*> by_rel;
    for (const ScanItem& item : items) by_rel[rel_of(item.notespath, input)] = &item;

    for (const auto& row : snapshot) {
        const std::string rel = row["path"].get<std::string>();
        auto it = by_rel.find(rel);
        REQUIRE_MESSAGE(it != by_rel.end(), "not discovered: " << rel);
        const ScanItem& item = *it->second;
        CHECK_MESSAGE(item.md5 == row["md5"].get<std::string>(), rel);
        CHECK_MESSAGE(item.title == row["title"].get<std::string>(), rel);
        CHECK_MESSAGE(item.artist == row["artist"].get<std::string>(), rel);
        CHECK_MESSAGE(item.charter == row["charter"].get<std::string>(), rel);
        CHECK_MESSAGE(rel_of(item.rootfolder, "") == row["folder"].get<std::string>(), rel);
    }
}

TEST_CASE("rescan cache reproduces the scan without reading chart files") {
    const std::string input = HYDRA_INPUT_DIR;
    auto [items, errors] = discover_charts({input});
    REQUIRE(errors.empty());
    REQUIRE(!items.empty());

    hydra::store::RecordStore store(":memory:");
    std::vector<hydra::store::ChartLibraryEntry> entries;
    for (const ScanItem& it : items)
        entries.push_back({it.md5, it.title, it.artist, it.charter, it.notespath,
                           it.rootfolder, it.sig});
    store.rebuild_chart_library(entries);

    hydra::store::ChartLibraryCache cache = store.chart_library_cache();
    CHECK(cache.size() == items.size());

    int last_cached = 0, last_done = 0;
    ScanCallbacks callbacks;
    callbacks.on_charts = [&](int done, int, int cached) {
        last_done = done;
        last_cached = cached;
    };
    auto [items2, errors2] = discover_charts({input}, callbacks, &cache);
    CHECK(errors2.empty());

    // Every chart came out of the cache (no file was opened for content)...
    CHECK(last_done == static_cast<int>(items.size()));
    CHECK(last_cached == static_cast<int>(items.size()));

    // ...and the results are identical, field for field, in the same order.
    REQUIRE(items2.size() == items.size());
    for (size_t i = 0; i < items.size(); ++i) {
        CHECK(items2[i].md5 == items[i].md5);
        CHECK(items2[i].title == items[i].title);
        CHECK(items2[i].artist == items[i].artist);
        CHECK(items2[i].charter == items[i].charter);
        CHECK(items2[i].notespath == items[i].notespath);
        CHECK(items2[i].rootfolder == items[i].rootfolder);
        CHECK(items2[i].sig == items[i].sig);
    }
}

TEST_CASE("run_batch files results under the lens it is given") {
    std::string chart;
    for (const std::string& p : corpus::chart_paths()) {
        if (!hydra::load_songpath(p, true, true).is_empty()) { chart = p; break; }
    }
    REQUIRE(!chart.empty());

    AnalysisSettings settings;
    settings.depth_mode = hydra::DepthMode::Scores;
    settings.depth_value = 10;
    settings.ms_filter = 10.0;
    const hydra::store::Lens lens =
        hydra::store::Lens::from(std::optional<int>(10), 0, 10);

    ScanItem item;
    item.md5 = hash_chart_file(chart);
    item.title = "t";
    item.notespath = chart;
    hydra::store::RecordStore store(":memory:");
    run_batch({item}, "lens-test", lens, settings, store, /*redo=*/false, 1);

    const hydra::store::CapQuery cap = hydra::store::CapQuery::from_setting(settings.sp_cap);
    CHECK(store.has_record(hydra::store::RecordKey{item.md5, "lens-test", cap, lens}));
}

namespace {

void write_sng_with_metadata(
    const std::filesystem::path& path,
    const std::vector<std::pair<std::string, std::string>>& metadata) {
    std::ofstream f(path, std::ios::binary);
    std::string header = "SNGPKG";
    header.resize(34, '\0');
    f.write(header.data(), static_cast<std::streamsize>(header.size()));
    auto put_le = [&f](uint64_t v, int bytes) {
        for (int i = 0; i < bytes; ++i) f.put(static_cast<char>((v >> (8 * i)) & 0xFF));
    };
    put_le(metadata.size(), 8);
    for (const auto& [key, value] : metadata) {
        put_le(key.size(), 4);
        f.write(key.data(), static_cast<std::streamsize>(key.size()));
        put_le(value.size(), 4);
        f.write(value.data(), static_cast<std::streamsize>(value.size()));
    }
}

}  // namespace

TEST_CASE("discover_charts: a song with no usable name reads (unknown)") {
    namespace fs = std::filesystem;
    const std::string chart = corpus::first_chart_with_suffix(".chart");
    REQUIRE(!chart.empty());

    const fs::path root = fs::temp_directory_path() /
        ("hydra_unknown_title_" + std::to_string(GetCurrentProcessId()));
    fs::remove_all(root);

    // An empty `name =` line.
    fs::create_directories(root / "empty_name");
    fs::copy_file(fs::u8path(chart), root / "empty_name" / "notes.chart");
    {
        std::ofstream ini(root / "empty_name" / "song.ini", std::ios::binary);
        ini << "[song]\nname =\nartist = Someone\n";
    }
    // No name line at all.
    fs::create_directories(root / "no_name");
    fs::copy_file(fs::u8path(chart), root / "no_name" / "notes.chart");
    {
        std::ofstream ini(root / "no_name" / "song.ini", std::ios::binary);
        ini << "[song]\nartist = Someone\n";
    }
    // A .sng whose embedded name is empty.
    write_sng_with_metadata(root / "blank.sng",
                            {{"name", ""}, {"artist", "Someone"}, {"charter", "C"}});

    auto [items, errors] = discover_charts({root.u8string()});
    fs::remove_all(root);
    CHECK(errors.empty());
    REQUIRE(items.size() == 3);
    for (const ScanItem& it : items) {
        CAPTURE(it.notespath);
        CHECK(it.title == hydra::kUnknownTitle);
        CHECK(it.artist == "Someone");
    }
}

TEST_CASE("rescan cache: an old placeholder or blank title reads (unknown)") {
    const std::string input = HYDRA_INPUT_DIR;
    auto [items, errors] = discover_charts({input});
    REQUIRE(!items.empty());

    // Library rows written before the fallback existed: a blank title from an
    // empty `name =`, or the old readers' "<unknown title>".
    hydra::store::RecordStore store(":memory:");
    std::vector<hydra::store::ChartLibraryEntry> entries;
    for (size_t i = 0; i < items.size(); ++i) {
        const ScanItem& it = items[i];
        entries.push_back({it.md5, i % 2 ? "<unknown title>" : "", it.artist, it.charter,
                           it.notespath, it.rootfolder, it.sig});
    }
    store.rebuild_chart_library(entries);
    hydra::store::ChartLibraryCache cache = store.chart_library_cache();

    auto [items2, errors2] = discover_charts({input}, ScanCallbacks{}, &cache);
    REQUIRE(items2.size() == items.size());
    for (const ScanItem& it : items2) CHECK(it.title == hydra::kUnknownTitle);
}

namespace {

// A fresh folder under %TEMP% for one scan fixture.
std::string scan_fixture_dir(const char* name) {
    wchar_t tmp[MAX_PATH];
    GetTempPathW(MAX_PATH, tmp);
    std::string dir = hydra::wide_to_utf8(tmp) + "hydra_scan_case_" +
                      std::to_string(GetCurrentProcessId()) + "_" + name;
    CreateDirectoryW(hydra::utf8_to_wide(dir).c_str(), nullptr);
    return dir;
}

void write_fixture(const std::string& path, const std::vector<uint8_t>& bytes) {
    FILE* f = hydra::fopen_utf8(path, L"wb");
    REQUIRE_MESSAGE(f != nullptr, "cannot write " << path);
    if (!bytes.empty()) std::fwrite(bytes.data(), 1, bytes.size(), f);
    std::fclose(f);
}

}  // namespace

TEST_CASE("discover_charts finds a folder whose notes and ini names are capitalized") {
    const std::string dir = scan_fixture_dir("caps");
    write_fixture(dir + "\\Notes.mid",
                  testmidi::smf(testmidi::concat({testmidi::track_name("PART DRUMS"),
                                                  testmidi::set_tempo(),
                                                  testmidi::note_on(96, 100),
                                                  testmidi::end_of_track()})));
    const std::string ini = "[song]\r\nname = Capital Case\r\nartist = Someone\r\n"
                            "charter = Someone Else\r\n";
    write_fixture(dir + "\\Song.ini", std::vector<uint8_t>(ini.begin(), ini.end()));

    auto [items, errors] = discover_charts({dir});
    REQUIRE(errors.empty());
    REQUIRE(items.size() == 1);
    CHECK(items[0].title == "Capital Case");
    CHECK(items[0].notespath == dir + "\\Notes.mid");
}
