// GENERATED by tools/gen_chord_tables.py from
// hydra/hyencode.py:CHORD_ENCODE / CHORD_DECODE. Do not edit by
// hand; re-run the generator instead.
//
// Chord hash -> display string, the reverse of what the
// scoring code hashes a chord to, plus the display-string ->
// note-field list needed by Chord::from_code.

#include "core/chord_tables.h"

namespace hydra {
namespace {

struct ChordEncodeEntry {
    int64_t hash;
    const char* code;
};

// 551 entries.
const ChordEncodeEntry kEntries[] = {
    {-9217201750852330787LL, "B)~~~;"},
    {-9201251245059988399LL, "B)~~~W"},
    {-9196491248920060957LL, "B."},
    {-9158868915942127459LL, "B)~1"},
    {-9114091088647197695LL, "N"},
    {-9094653362094891323LL, "s"},
    {-9061190903496980029LL, "O"},
    {-8968546742996496176LL, "B)~E"},
    {-8943507536709453094LL, "B)~~~o"},
    {-8914220793219985786LL, "B)|"},
    {-8906958065621952042LL, "B)~S"},
    {-8873612245398812787LL, "b"},
    {-8830515713709625984LL, "B)~~h"},
    {-8684590436363718459LL, "B)~7"},
    {-8676420677319491501LL, "V"},
    {-8627724273451623450LL, "B)~~|"},
    {-8620156760406222701LL, "B)~a"},
    {-8608286546899317078LL, "B)~~}"},
    {-8594285996568762649LL, "B)~f"},
    {-8589427339798795802LL, "B)~~~A"},
    {-8576037975943929661LL, "B)<"},
    {-8573398323675113060LL, "B)~|"},
    {-8563111526464951009LL, "B)~~~'"},
    {-8562728368608751290LL, "BT"},
    {-8557869711838784443LL, "BM"},
    {-8557809223663283258LL, "B){"},
    {-8546751232454462353LL, "B+"},
    {-8388408412845114444LL, "B)~$"},
    {-8382806933110377734LL, "B)~~~P"},
    {-8371699762600541874LL, "B#"},
    {-8329789488590580824LL, "B)~~~z"},
    {-8302856596596087548LL, "B)5"},
    {-8237874427012060121LL, "B)~d"},
    {-8221957779033272369LL, "B)g"},
    {-8190339662897759825LL, "B)z"},
    {-8102575022903030601LL, "Bi"},
    {-8070682999856822162LL, "Bq"},
    {-8023846338309847903LL, "B)~/"},
    {-7959630784462611767LL, "7"},
    {-7870366710319949596LL, "B)~M"},
    {-7831168191635510839LL, "B)y"},
    {-7799718209124179609LL, "B)~,"},
    {-7789146024475533022LL, "Q"},
    {-7766555444648838398LL, "B)1"},
    {-7691432935138786043LL, "B5"},
    {-7614871157028902319LL, "BS"},
    {-7524663439602928036LL, "B)~~*"},
    {-7493333488760677080LL, "B)~~S"},
    {-7463698630869987406LL, "f"},
    {-7264459906102769441LL, "B)Y"},
    {-7233605465695058886LL, "$"},
    {-7215420859269431760LL, "B)~~d"},
    {-7195983132717125388LL, "B)~~e"},
    {-7180163876980519577LL, "R"},
    {-7151547948387665254LL, "B)~~~/"},
    {-7116659725163461236LL, "B)-"},
    {-7097221998611154864LL, "B)B"},
    {-7082269892996774409LL, "Bt"},
    {-7040766051391461983LL, "B)6"},
    {-6960780932641522541LL, "B)A"},
    {-6939496257662455438LL, "B)~~8"},
    {-6906551705233993678LL, "B)~:"},
    {-6874266432015134514LL, "B)~~4"},
    {-6872988623189175378LL, "B4"},
    {-6827297350192777835LL, "B)L"},
    {-6809129086087632617LL, "`"},
    {-6798842164253727497LL, "B)~~~i"},
    {-6760248155606758708LL, "B)~~ "},
    {-6740810429054452336LL, "B)~~!"},
    {-6695635408620086267LL, "B)~~~0"},
    {-6634066307359225908LL, "B)~~~N"},
    {-6632233470482536948LL, "j"},
    {-6610369681715389663LL, "B)~)"},
    {-6574760679500692316LL, "B)~~i"},
    {-6558400761347736024LL, "BQ"},
    {-6492660875461684730LL, "B)t"},
    {-6455378407703357583LL, "B)d"},
    {-6426139708280760856LL, "B)~q"},
    {-6425522629620112373LL, "B)~m"},
    {-6392778594841235275LL, "B)$"},
    {-6386675827004082205LL, "B)~~~g"},
    {-6285576228294199679LL, "B)!"},
    {-6273812285916092757LL, "BG"},
    {-6203919999289343995LL, "B)r"},
    {-6125191314696161297LL, "B)s"},
    {-6115944728391608206LL, "B)Q"},
    {-6115497078468704535LL, "B)~~3"},
    {-6107346573490140522LL, "B)~~C"},
    {-6101272031425224954LL, "q"},
    {-6087908846937834150LL, "B)~~N"},
    {-6078327428859670386LL, "B)~'"},
    {-6060960555084845832LL, "B)~~`"},
    {-5967460203602085597LL, "B)~~~c"},
    {-5953866945500242215LL, "B)~~~B"},
    {-5949556650040007476LL, "B)~~z"},
    {-5836832425899177538LL, "B)~~X"},
    {-5783195085001742963LL, "X"},
    {-5755113651289466975LL, "e"},
    {-5750935003933437994LL, "B)~~L"},
    {-5750317925272789511LL, "B)~~G"},
    {-5731497277381131622LL, "B<"},
    {-5705211937644407604LL, "B)~I"},
    {-5680172731357364522LL, "B>"},
    {-5668661696267933827LL, "B)E"},
    {-5666753276073682394LL, "B0"},
    {-5660511191289369814LL, "B)~4"},
    {-5597455375943539687LL, "B)~~~@"},
    {-5583965030996130274LL, "B)p"},
    {-5548560710203821045LL, "B)4"},
    {-5535806398240226474LL, "B)~O"},
    {-5533790466764435798LL, "t"},
    {-5469530530878343573LL, "B)~~u"},
    {-5467411821743913319LL, "B)~X"},
    {-5389919409624055325LL, "w"},
    {-5348800368087705076LL, "B)~H"},
    {-5304099621732667286LL, "B))"},
    {-5301574122877767370LL, "B)e"},
    {-5276152929215367312LL, "B@"},
    {-5273187456766440759LL, "B)~ "},
    {-5227553461439427746LL, "B)M"},
    {-5216495470230606841LL, "h"},
    {-5211636813460639994LL, "B)~K"},
    {-5177378897207733270LL, "}"},
    {-5166787893520425069LL, " "},
    {-5113118961321641045LL, "B)C"},
    {-5102060970112820140LL, "BJ"},
    {-5096227700885409733LL, "B)~~D"},
    {-5063765539876046628LL, "i"},
    {-5014571471880554049LL, "B)q"},
    {-5012663051686302616LL, "B)a"},
    {-4964111446588168798LL, "B)~~~K"},
    {-4948394003345250775LL, "B)~~0"},
    {-4943365151556159909LL, "B)~~~+"},
    {-4936630060967143853LL, "B)~3"},
    {-4872196385009648095LL, "B2"},
    {-4863533886602137772LL, "B!"},
    {-4860083900673904313LL, "B)o"},
    {-4809909336442209837LL, "BR"},
    {-4760208122631217530LL, "m"},
    {-4745649400556117612LL, "B)~~r"},
    {-4647483898490387592LL, "B)~~Q"},
    {-4607699877031466270LL, "B)~~~n"},
    {-4563660849088861000LL, "|"},
    {-4557546589073260216LL, "B)~B"},
    {-4403796553074515002LL, "B)~w"},
    {-4382495119219339737LL, "Bs"},
    {-4359322136106127039LL, "B)~Y"},
    {-4358705057445478556LL, "B'"},
    {-4358307864306042251LL, "B)~."},
    {-4339884409553820667LL, "B$"},
    {-4337458347338979754LL, "B)~~>"},
    {-4280766360803145836LL, "B)~~-"},
    {-4261328634250839464LL, "B)~~9"},
    {-4255682703801100115LL, "B)~~~9"},
    {-4201135019516557688LL, "B)~C"},
    {-4166688014735994146LL, "W"},
    {-4146809069740047298LL, "B)~@"},
    {-4115441645634668315LL, "B)~t"},
    {-4052549356798422754LL, "Z"},
    {-4036326992308991569LL, "A"},
    {-4034454459250591137LL, "U"},
    {-3890622965138209046LL, "B)~2"},
    {-3888213143035576682LL, "B)~~~7"},
    {-3843095949475439642LL, "B)~~("},
    {-3834658387257725146LL, "B)~~~?"},
    {-3785763721518006504LL, "BK"},
    {-3763902240613275030LL, "B)P"},
    {-3749464057858297065LL, "B)l"},
    {-3747972084869144882LL, "5"},
    {-3697542849658415496LL, "B)["},
    {-3635029557740510364LL, "B)~~k"},
    {-3599935703899048577LL, "6"},
    {-3531801573478874154LL, "B)~~~5"},
    {-3496913350254670136LL, "B)~~&"},
    {-3480969394973906059LL, "F"},
    {-3467188826492201713LL, "B)~~~="},
    {-3446607244079446073LL, "E"},
    {-3432300603267997695LL, "B)~~~8"},
    {-3377947041329527618LL, "Bv"},
    {-3332172743961659372LL, "B);"},
    {-3311425874148603744LL, "B)~~v"},
    {-3292805675994887377LL, "B)~~~J"},
    {-3226371623175644624LL, "B)="},
    {-3215370820837016972LL, "P"},
    {-3204510142270913150LL, "B)~R"},
    {-3194223220437008030LL, "B)~~~F"},
    {-3108017355229952727LL, "B)~~~,"},
    {-3105496894056250673LL, "B~"},
    {-3102646596696187034LL, "B)~~~V"},
    {-3076399239094440183LL, "B)x"},
    {-3075889033711295167LL, "B)~~~6"},
    {-3061168710691058011LL, "9"},
    {-3011786492107767742LL, "BE"},
    {-3010477480564004185LL, "B)~<"},
    {-2955014304591901216LL, "B)~~t"},
    {-2906488222893126353LL, "B)~~5"},
    {-2900648103377135701LL, "o"},
    {-2873590052592890769LL, "D"},
    {-2858959251280314444LL, "B)~~~m"},
    {-2852609923039519634LL, "B)S"},
    {-2760601234276955204LL, "B)~o"},
    {-2751605785673250199LL, "B8"},
    {-2740547794464429294LL, "B)J"},
    {-2708929678328916750LL, "B)w"},
    {-2654065911007301657LL, "B)("},
    {-2644316931342244309LL, "B)~="},
    {-2590622552225727863LL, "B["},
    {-2541309069697211329LL, "B)~~I"},
    {-2531727651619047565LL, "B)~%"},
    {-2496198353482817106LL, "~"},
    {-2487600198581349422LL, "B)~~P"},
    {-2460651906728361104LL, "B)~~c"},
    {-2459652840692355645LL, "Bl"},
    {-2394144272255081044LL, "BB"},
    {-2384136224907726766LL, "B)~~~)"},
    {-2349248001683522748LL, "B)~~~#"},
    {-2329810275131216376LL, "B)~~~$"},
    {-2301108945041302723LL, "B)~~~T"},
    {-2284635254696850307LL, "B)~~~("},
    {-2223193045005097247LL, "g"},
    {-2171911030556020369LL, "B)~~["},
    {-2143787170024957155LL, "c"},
    {-2079353494067461397LL, "L"},
    {-2040764816380578714LL, "B)~9"},
    {-2017066445500023139LL, "4"},
    {-2011061477837434577LL, "Bz"},
    {-1976331140423082956LL, "B)~i"},
    {-1932465263249466143LL, "B)~Z"},
    {-1914044091855644698LL, "B) "},
    {-1870962636971420810LL, "B)~6"},
    {-1859891292848122765LL, "B)~~~G"},
    {-1850746488639755580LL, "B)~~~L"},
    {-1782539716150781350LL, "B)~~H"},
    {-1768314669107301769LL, "B)%"},
    {-1765464371747238130LL, "M"},
    {-1745370066541747201LL, "B)~0"},
    {-1681154512694511065LL, "'"},
    {-1677548632692480257LL, "B)~l"},
    {-1636652727534610201LL, "B)~~]"},
    {-1608861579657559523LL, "B)~g"},
    {-1447387425323756139LL, "d"},
    {-1445482594685856204LL, "Bx"},
    {-1344365071679377698LL, "B)~~~{"},
    {-1335704333950010642LL, "B),"},
    {-1323558476318599730LL, "B)~&"},
    {-1252450010100856995LL, "B)~e"},
    {-1243484101366804871LL, ";"},
    {-1214225424051243192LL, "B)~~y"},
    {-1194787697498936820LL, "Be"},
    {-1194545426670098661LL, "B)7"},
    {-1180787147168382391LL, "x"},
    {-1159899474274732802LL, "B)~{"},
    {-1140461747722426430LL, "B)b"},
    {-1128449491763401572LL, "B)~~E"},
    {-1080110926552311960LL, "z"},
    {-1040822567808847557LL, "B9"},
    {-1002925577100050556LL, ")"},
    {-982562503147230423LL, "B)~~Y"},
    {-949870357157691104LL, "B)~~~O"},
    {-947020059797627465LL, "B)~~~D"},
    {-942161403027660618LL, "B)i"},
    {-937800214164469116LL, "B)&"},
    {-916290639190200566LL, "Br"},
    {-873071676619564552LL, "B)~~~1"},
    {-824375577611679863LL, "B)~b"},
    {-803487904718030274LL, "B)~y"},
    {-792429913509209369LL, "B)#"},
    {-776840813497379567LL, "v"},
    {-721226759479959679LL, "u"},
    {-681614109562630864LL, "B)~5"},
    {-661019985894354736LL, "B)~~<"},
    {-640718204404760808LL, "BV"},
    {-610347488909467645LL, "B)~*"},
    {-593191188741991404LL, "B)~~@"},
    {-548821078424677133LL, "BL"},
    {-540455202282718883LL, "B)m"},
    {-515132997278183587LL, "B)~v"},
    {-499962785052700679LL, "B;"},
    {-456867860919569338LL, "B)~L"},
    {-436018343952506841LL, "B)~x"},
    {-428450830907106092LL, "B)~`"},
    {-426020702164932182LL, "B)~~m"},
    {-396940431408322238LL, "B)~~~|"},
    {-353757198714436246LL, "B-"},
    {-333463165676373210LL, "Bg"},
    {-288071178640280840LL, "B)~~~f"},
    {-268325819748871313LL, "!"},
    {-214184603693584028LL, "B)v"},
    {-147663436512660154LL, "B)~u"},
    {-111150667096970939LL, "B)h"},
    {-91648854282841863LL, "B)~~~Q"},
    {-29470870642798805LL, "B)~~~x"},
    {-17362767600066442LL, "Bu"},
    {-5196899261308715LL, "B)n"},
    {14785635138570152LL, "B)~~~`"},
    {22275191993674370LL, "B,"},
    {109237600856477986LL, "B)~~o"},
    {141386003595114580LL, "B)~~g"},
    {148525959599942389LL, "B&"},
    {198077990130948498LL, "B)~~W"},
    {217515716683254870LL, "B)U"},
    {235173903092019077LL, "B)~~q"},
    {301353200427395687LL, "8"},
    {316276850789225394LL, "S"},
    {326940698913903723LL, "B)k"},
    {387311867791257800LL, "B)V"},
    {389744752759197803LL, "B)~~~t"},
    {392170524561224647LL, "B?"},
    {404375554071774128LL, "B)~~~y"},
    {474002591737924820LL, "B)~~6"},
    {493440318290231192LL, "B)~~7"},
    {550043938159980320LL, "Bn"},
    {583493304459626120LL, "B)0"},
    {622453367938732261LL, "B):"},
    {639327306906402341LL, "B)~r"},
    {672688420345927922LL, "B)~}"},
    {693989854201103187LL, "B3"},
    {746156322315900331LL, "B)j"},
    {781265378917843310LL, "."},
    {798870268593460722LL, "B)D"},
    {801720565953524361LL, "BO"},
    {823184745069122112LL, "Y"},
    {962210275409625612LL, "B)~~~b"},
    {987359141119619402LL, "B)'"},
    {1006796867671925774LL, "B)~p"},
    {1046260748948604425LL, "B)R"},
    {1109436036502342200LL, "B)~~~h"},
    {1185862008282233878LL, "B)Z"},
    {1258607301261223047LL, "BW"},
    {1276543592326112039LL, "B)~]"},
    {1288307534704218961LL, "]"},
    {1317439497483982095LL, "B)~~2"},
    {1325590002462546108LL, "B)c"},
    {1335111120211940793LL, "B)~~~."},
    {1335171420540709872LL, "B)+"},
    {1352538294315534426LL, "B)~~T"},
    {1459631903900138043LL, "B)~~~<"},
    {1572356128040967981LL, "B)~~_"},
    {1662563845466942264LL, "B)~~B"},
    {1682001572019248636LL, "B)~~K"},
    {1708286911755972654LL, "B)~F"},
    {1733326118043015736LL, "B)~~~w"},
    {1763526260889721978LL, "B)~~~_"},
    {1766183299879004236LL, "="},
    {1807006169330844743LL, "1"},
    {1816043473456840571LL, "B)~~~>"},
    {1843950298086158801LL, "B:"},
    {1919154135661973663LL, "B|"},
    {1965524754208773311LL, "BY"},
    {2064698481312675182LL, "B)~G"},
    {2089737687599718264LL, "B*"},
    {2119024431089185572LL, "B)}"},
    {2224245725897031012LL, "B)~~~^"},
    {2298784563911132146LL, "I"},
    {2335936874096030268LL, "<"},
    {2405520950857547908LL, "B)~~~ "},
    {2420273524266384014LL, "{"},
    {2438959227740408709LL, "B)~h"},
    {2470133697844220349LL, "B)~~~*"},
    {2553414948726475945LL, "@"},
    {2568290651170817374LL, "B)]"},
    {2573892130905554084LL, "B)~~~]"},
    {2667849448844262646LL, "Bm"},
    {2703444590788140793LL, "T"},
    {2759504028918441180LL, "0"},
    {2805798972368913988LL, "B)~~~I"},
    {2806466944432519234LL, "B)2"},
    {2849838000311519258LL, "B)^"},
    {3009398885999323455LL, "BH"},
    {3054176713294253219LL, "^"},
    {3073614439846559591LL, "BX"},
    {3095478228613706876LL, "B)~~="},
    {3144019710170976781LL, "B)~_"},
    {3152170215149540794LL, "B)~~,"},
    {3177134457618562560LL, "n"},
    {3202077032673660519LL, "B)O"},
    {3212363829883822570LL, "B)~A"},
    {3217307561077042691LL, "-"},
    {3266689779660332960LL, "B)~?"},
    {3350394859170692762LL, "B)~~l"},
    {3468270308365864200LL, "B{"},
    {3634315043445634951LL, "B)_"},
    {3780202032061806100LL, ">"},
    {3792502160035204302LL, "B)~#"},
    {3797495703322498642LL, "B)~~~R"},
    {3817824365039739598LL, "B)~~f"},
    {3833000872053638053LL, "#"},
    {3833398065193074358LL, "B)~-"},
    {3838478313350870090LL, "B)~~~r"},
    {3838999544927811068LL, "B)~~~U"},
    {3881697275921506104LL, "B)~~~3"},
    {3911074355854502988LL, "B)~~~Y"},
    {3916585499145710122LL, "B)~~$"},
    {3936023225698016494LL, "B)~~%"},
    {3946310022908178545LL, "B)f"},
    {3981198246132382563LL, "B)~~~2"},
    {4070636510231640434LL, "B)3"},
    {4081150425646405659LL, "%"},
    {4102072975251776514LL, "B)~~j"},
    {4205947874116393523LL, "BA"},
    {4272997068702412650LL, "B)~~#"},
    {4317610221333664057LL, "+"},
    {4333368237579766727LL, "l"},
    {4337609815689085091LL, "B)~~~4"},
    {4401011753826634410LL, "k"},
    {4403021368836376073LL, "B^"},
    {4458484544808479042LL, "B)~~s"},
    {4554539598120065814LL, "B="},
    {4560888926360860624LL, "B%"},
    {4588284868136752613LL, "B)~n"},
    {4607105516028410502LL, "B)~s"},
    {4673613150501690562LL, "B)~Q"},
    {4704569171071463508LL, "?"},
    {4728231269462665307LL, "B)~~F"},
    {4750102339882885991LL, "B)~^"},
    {4759432938393078601LL, "B)~;"},
    {4917300495917563152LL, "B)~V"},
    {4922058441300701562LL, "B)~~'"},
    {4925898650819030836LL, "B)~~O"},
    {4952846942672019154LL, "B)~~a"},
    {4954917795449500972LL, "B)~("},
    {4965334306323471985LL, "r"},
    {4972284669224325526LL, "B)~~b"},
    {4976355925164550702LL, "B "},
    {5029362624492653492LL, "B)~~~&"},
    {5052959153661736983LL, "B)~["},
    {5064250847716857510LL, "B)~~{"},
    {5079378278808929143LL, "B)~~~C"},
    {5083688574269163882LL, "B)~~~!"},
    {5131827630911383907LL, "B)~~~S"},
    {5134677928271447546LL, "B)~~~M"},
    {5225010933020385313LL, "p"},
    {5258693846467398011LL, "B)~~~Z"},
    {5261025545396666261LL, "B)~~Z"},
    {5282310220375733364LL, "B)~~M"},
    {5320316503437542587LL, "B)~~U"},
    {5328033286664763754LL, "B)~J"},
    {5346257839668662643LL, "*"},
    {5372734033019801544LL, "Bh"},
    {5449280193313041084LL, "B)N"},
    {5460692339786449344LL, "G"},
    {5499454757544735560LL, "B]"},
    {5549297261092022754LL, "B)~~~k"},
    {5563714693430827785LL, "B/"},
    {5630446149551930480LL, "B)`"},
    {5668128782858633057LL, "B)~+"},
    {5729145602576504072LL, "B)~8"},
    {5737654568541497674LL, "Bp"},
    {5796283848418076429LL, "B)."},
    {5804637269742820735LL, "Bb"},
    {5821608410848531364LL, "B)~N"},
    {5847019604236439917LL, "&"},
    {5855866327101438088LL, "B)~W"},
    {5897216722918635120LL, "B)*"},
    {5950041957880818358LL, "B)9"},
    {5968512884494019362LL, "B)X"},
    {6065413494411614211LL, "B)~~1"},
    {6069133777721002560LL, "B)~~~v"},
    {6089940373081780528LL, "BN"},
    {6144607203273778823LL, "B)~U"},
    {6161048839299523263LL, "B)~c"},
    {6172909594987536841LL, "Bf"},
    {6218711151901443438LL, "B)~~x"},
    {6273037101677953828LL, "B)~z"},
    {6330777152512021392LL, "B)?"},
    {6350278965326150468LL, "B)~P"},
    {6366323599266477394LL, "B)~~R"},
    {6414359460429175259LL, "("},
    {6422353776252842388LL, "BD"},
    {6425545347277705088LL, "B)~~~s"},
    {6457409933847303961LL, "B)~!"},
    {6475698635235911142LL, "B)~D"},
    {6514157296806636352LL, "B)~k"},
    {6589123271788700395LL, "J"},
    {6629448671234656356LL, "B)T"},
    {6673923088203044319LL, "Ba"},
    {6679865506295188991LL, "BU"},
    {6739152913850365243LL, "H"},
    {6752478863506025522LL, "B)~~:"},
    {6771916590058331894LL, "B)~~;"},
    {6832110204792613670LL, "B1"},
    {6839745387210695226LL, "B)~~?"},
    {6842175267494743684LL, "B`"},
    {6849326805288858990LL, "B)F"},
    {6917803578674503043LL, "Bo"},
    {6920435271506601725LL, "B}"},
    {6921401616215550910LL, "K"},
    {6956630988480810920LL, "B)>"},
    {6977480505447873417LL, "B("},
    {7059741650685944012LL, "2"},
    {7199314245706796230LL, "B)u"},
    {7234398947867584024LL, ":"},
    {7254762021820404157LL, "B)~~/"},
    {7265835412887720104LL, "B7"},
    {7312094249777837295LL, "B)~~~j"},
    {7333955730682568769LL, "Bd"},
    {7384027978757581453LL, "By"},
    {7411470086005893941LL, "Bj"},
    {7483544896932585861LL, "B)~~~X"},
    {7486395194292649500LL, "B)W"},
    {7497412062013650206LL, "/"},
    {7497922267396795222LL, "B)H"},
    {7566783806472319663LL, "["},
    {7600944621041173663LL, "B)~~~:"},
    {7604606952852589914LL, "Bw"},
    {7618796996516189173LL, "B_"},
    {7620207022115788857LL, "B)~~~d"},
    {7631014566083635128LL, "B)~~V"},
    {7721819350160567614LL, "B)~~w"},
    {7740439548314283981LL, "B)~~~p"},
    {7803243602159578061LL, "3"},
    {7817874403472154386LL, "B)~~~u"},
    {7822205515434840190LL, "BF"},
    {7887501441138305078LL, "B)~~+"},
    {7893347829024930649LL, "B)~T"},
    {7906939167690611450LL, "BI"},
    {7908310603700614313LL, "B)~~~["},
    {7925227869079218631LL, "B)K"},
    {7972076513618113347LL, "B)G"},
    {8021458732201403616LL, "B)~>"},
    {8077612947625273283LL, "C"},
    {8086187269746308180LL, "y"},
    {8113159394379729285LL, "B)8"},
    {8131067296876279744LL, "B)~~."},
    {8159655171716280589LL, "B)~~~l"},
    {8174285973028856914LL, "B)~~~q"},
    {8180635301269651724LL, "BC"},
    {8186509030237807894LL, "_"},
    {8276954285492450893LL, "B)~j"},
    {8300943530355594595LL, "BP"},
    {8304839506242260165LL, "B)~~~E"},
    {8358673060102161456LL, "B)/"},
    {8395146851362312242LL, "B)~~~a"},
    {8420295717072306032LL, "a"},
    {8424971412396884253LL, "BZ"},
    {8426879832591135686LL, "B)~~p"},
    {8428606132046340817LL, "Bc"},
    {8472498428059653657LL, "B)~~J"},
    {8577980313151401957LL, "Bk"},
    {8666325599897689912LL, "B)I"},
    {8683997222625648610LL, "B)~~~%"},
    {8731462945825191809LL, ","},
    {8748609969612321051LL, "B)~~~-"},
    {8885695783700219796LL, "B)@"},
    {8954538949704674122LL, "B)~~~e"},
    {9005292703993654611LL, "B)~~^"},
    {9095500421419628894LL, "B)~~A"},
    {9122238139665268899LL, "B)~~)"},
    {9146824967443395994LL, "B6"},
    {9153916204908742221LL, "B)~~~H"},
    {9207075620396759641LL, "B)~~n"},
};

struct ChordDecodeNote {
    int color;
    int dyn;
    int cym;
    int is2x;
};
struct ChordDecodeEntry {
    const char* code;
    const ChordDecodeNote* notes;
    int count;
};

const ChordDecodeNote kDecodeNotes0[] = {{1, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes1[] = {{2, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes2[] = {{1, 1, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes3[] = {{1, 1, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes4[] = {{3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes5[] = {{1, 1, 1, 1}};
const ChordDecodeNote kDecodeNotes6[] = {{1, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes7[] = {{4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes8[] = {{2, 1, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes9[] = {{3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes10[] = {{1, 1, 1, 0}, {2, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes11[] = {{2, 1, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes12[] = {{2, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes13[] = {{5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes14[] = {{4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes15[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes16[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes17[] = {{5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes18[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes19[] = {{2, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes20[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes21[] = {{1, 1, 1, 1}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes22[] = {{1, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes23[] = {{1, 1, 1, 1}, {2, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes24[] = {{2, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes25[] = {{2, 1, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes26[] = {{1, 1, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes27[] = {{1, 1, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes28[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes29[] = {{1, 1, 1, 1}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes30[] = {{4, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes31[] = {{3, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes32[] = {{1, 1, 1, 0}, {4, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes33[] = {{1, 1, 1, 1}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes34[] = {{3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes35[] = {{2, 3, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes36[] = {{1, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes37[] = {{2, 3, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes38[] = {{4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes39[] = {{1, 1, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes40[] = {{1, 1, 1, 1}, {4, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes41[] = {{2, 2, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes42[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes43[] = {{1, 1, 1, 1}, {4, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes44[] = {{1, 1, 1, 1}, {4, 1, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes45[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes46[] = {{4, 3, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes47[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes48[] = {{3, 3, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes49[] = {{3, 2, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes50[] = {{2, 1, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes51[] = {{3, 2, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes52[] = {{3, 2, 2, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes53[] = {{1, 1, 1, 1}, {4, 1, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes54[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes55[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes56[] = {{3, 2, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes57[] = {{4, 2, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes58[] = {{4, 3, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes59[] = {{2, 1, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes60[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes61[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes62[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes63[] = {{3, 1, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes64[] = {{1, 1, 1, 1}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes65[] = {{1, 1, 1, 1}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes66[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes67[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes68[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes69[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes70[] = {{4, 3, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes71[] = {{2, 3, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes72[] = {{2, 3, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes73[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes74[] = {{1, 1, 1, 0}, {4, 1, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes75[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes76[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes77[] = {{3, 1, 2, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes78[] = {{3, 2, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes79[] = {{2, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes80[] = {{1, 1, 1, 1}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes81[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes82[] = {{1, 1, 1, 0}, {4, 3, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes83[] = {{1, 1, 1, 0}, {4, 3, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes84[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes85[] = {{3, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes86[] = {{3, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes87[] = {{4, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes88[] = {{2, 2, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes89[] = {{2, 3, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes90[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes91[] = {{2, 3, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes92[] = {{1, 1, 1, 0}, {4, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes93[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes94[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes95[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes96[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes97[] = {{3, 3, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes98[] = {{3, 2, 2, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes99[] = {{3, 3, 2, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes100[] = {{3, 3, 2, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes101[] = {{2, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes102[] = {{1, 1, 1, 1}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes103[] = {{1, 1, 1, 1}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes104[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes105[] = {{1, 1, 1, 0}, {4, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes106[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes107[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes108[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes109[] = {{1, 1, 1, 0}, {4, 3, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes110[] = {{1, 1, 1, 0}, {4, 3, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes111[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes112[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes113[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes114[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes115[] = {{3, 1, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes116[] = {{3, 1, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes117[] = {{3, 1, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes118[] = {{3, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes119[] = {{3, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes120[] = {{3, 1, 2, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes121[] = {{3, 1, 2, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes122[] = {{3, 1, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes123[] = {{3, 1, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes124[] = {{3, 1, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes125[] = {{3, 1, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes126[] = {{4, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes127[] = {{4, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes128[] = {{4, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes129[] = {{4, 1, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes130[] = {{4, 1, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes131[] = {{4, 1, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes132[] = {{4, 1, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes133[] = {{3, 2, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes134[] = {{3, 2, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes135[] = {{3, 2, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes136[] = {{3, 2, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes137[] = {{3, 2, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes138[] = {{3, 2, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes139[] = {{3, 2, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes140[] = {{3, 2, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes141[] = {{3, 3, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes142[] = {{3, 3, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes143[] = {{3, 3, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes144[] = {{3, 3, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes145[] = {{3, 3, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes146[] = {{3, 3, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes147[] = {{3, 3, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes148[] = {{3, 3, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes149[] = {{3, 3, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes150[] = {{3, 2, 2, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes151[] = {{3, 2, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes152[] = {{3, 2, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes153[] = {{3, 2, 2, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes154[] = {{3, 2, 2, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes155[] = {{3, 2, 2, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes156[] = {{3, 2, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes157[] = {{3, 2, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes158[] = {{3, 3, 2, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes159[] = {{3, 3, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes160[] = {{3, 3, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes161[] = {{4, 2, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes162[] = {{4, 2, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes163[] = {{4, 2, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes164[] = {{4, 2, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes165[] = {{4, 3, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes166[] = {{4, 3, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes167[] = {{4, 3, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes168[] = {{4, 3, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes169[] = {{4, 2, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes170[] = {{4, 2, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes171[] = {{4, 2, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes172[] = {{4, 2, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes173[] = {{4, 2, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes174[] = {{4, 2, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes175[] = {{4, 3, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes176[] = {{4, 3, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes177[] = {{4, 3, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes178[] = {{4, 3, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes179[] = {{2, 3, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes180[] = {{2, 2, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes181[] = {{2, 3, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes182[] = {{2, 1, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes183[] = {{2, 3, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes184[] = {{2, 1, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes185[] = {{2, 2, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes186[] = {{2, 3, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes187[] = {{2, 2, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes188[] = {{1, 1, 1, 1}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes189[] = {{1, 1, 1, 1}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes190[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes191[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes192[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes193[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes194[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes195[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes196[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes197[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes198[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes199[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes200[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes201[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes202[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes203[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes204[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes205[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes206[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes207[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes208[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes209[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes210[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes211[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes212[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes213[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes214[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes215[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes216[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes217[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes218[] = {{1, 1, 1, 0}, {4, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes219[] = {{1, 1, 1, 1}, {4, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes220[] = {{1, 1, 1, 1}, {4, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes221[] = {{1, 1, 1, 0}, {4, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes222[] = {{1, 1, 1, 1}, {4, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes223[] = {{1, 1, 1, 1}, {4, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes224[] = {{1, 1, 1, 0}, {4, 1, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes225[] = {{1, 1, 1, 1}, {4, 1, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes226[] = {{1, 1, 1, 0}, {4, 1, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes227[] = {{1, 1, 1, 1}, {4, 1, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes228[] = {{1, 1, 1, 1}, {4, 1, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes229[] = {{1, 1, 1, 0}, {4, 1, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes230[] = {{1, 1, 1, 1}, {4, 1, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes231[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes232[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes233[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes234[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes235[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes236[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes237[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes238[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes239[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes240[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes241[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes242[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes243[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes244[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes245[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes246[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes247[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes248[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes249[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes250[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes251[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes252[] = {{1, 1, 1, 1}, {3, 2, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes253[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes254[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes255[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes256[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes257[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes258[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes259[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes260[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes261[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes262[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes263[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes264[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes265[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes266[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes267[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes268[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes269[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes270[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes271[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes272[] = {{1, 1, 1, 1}, {3, 3, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes273[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes274[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes275[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes276[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes277[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes278[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes279[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes280[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes281[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes282[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes283[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes284[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes285[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes286[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes287[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes288[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes289[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes290[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes291[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes292[] = {{1, 1, 1, 0}, {3, 2, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes293[] = {{1, 1, 1, 1}, {3, 2, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes294[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes295[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes296[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes297[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes298[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes299[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes300[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes301[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes302[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes303[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes304[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes305[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes306[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes307[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes308[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes309[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes310[] = {{1, 1, 1, 1}, {3, 3, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes311[] = {{1, 1, 1, 0}, {4, 2, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes312[] = {{1, 1, 1, 1}, {4, 2, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes313[] = {{1, 1, 1, 0}, {4, 2, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes314[] = {{1, 1, 1, 1}, {4, 2, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes315[] = {{1, 1, 1, 1}, {4, 2, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes316[] = {{1, 1, 1, 0}, {4, 2, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes317[] = {{1, 1, 1, 1}, {4, 2, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes318[] = {{1, 1, 1, 0}, {4, 2, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes319[] = {{1, 1, 1, 1}, {4, 2, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes320[] = {{1, 1, 1, 0}, {4, 2, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes321[] = {{1, 1, 1, 1}, {4, 2, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes322[] = {{1, 1, 1, 0}, {4, 3, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes323[] = {{1, 1, 1, 1}, {4, 3, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes324[] = {{1, 1, 1, 1}, {4, 3, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes325[] = {{1, 1, 1, 0}, {4, 3, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes326[] = {{1, 1, 1, 1}, {4, 3, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes327[] = {{1, 1, 1, 1}, {4, 3, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes328[] = {{1, 1, 1, 0}, {4, 3, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes329[] = {{1, 1, 1, 1}, {4, 3, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes330[] = {{1, 1, 1, 1}, {4, 3, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes331[] = {{1, 1, 1, 0}, {4, 2, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes332[] = {{1, 1, 1, 1}, {4, 2, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes333[] = {{1, 1, 1, 0}, {4, 2, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes334[] = {{1, 1, 1, 1}, {4, 2, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes335[] = {{1, 1, 1, 0}, {4, 2, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes336[] = {{1, 1, 1, 1}, {4, 2, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes337[] = {{1, 1, 1, 0}, {4, 2, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes338[] = {{1, 1, 1, 1}, {4, 2, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes339[] = {{1, 1, 1, 0}, {4, 2, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes340[] = {{1, 1, 1, 1}, {4, 2, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes341[] = {{1, 1, 1, 0}, {4, 2, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes342[] = {{1, 1, 1, 1}, {4, 2, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes343[] = {{1, 1, 1, 1}, {4, 3, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes344[] = {{1, 1, 1, 1}, {4, 3, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes345[] = {{1, 1, 1, 0}, {4, 3, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes346[] = {{1, 1, 1, 1}, {4, 3, 2, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes347[] = {{1, 1, 1, 0}, {4, 3, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes348[] = {{1, 1, 1, 1}, {4, 3, 2, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes349[] = {{1, 1, 1, 0}, {4, 3, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes350[] = {{1, 1, 1, 1}, {4, 3, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes351[] = {{1, 1, 1, 1}, {4, 3, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes352[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes353[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes354[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes355[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes356[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes357[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes358[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes359[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes360[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes361[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes362[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes363[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes364[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes365[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes366[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes367[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes368[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes369[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes370[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes371[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes372[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes373[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes374[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes375[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes376[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes377[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes378[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes379[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes380[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes381[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes382[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes383[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes384[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes385[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes386[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes387[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes388[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes389[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes390[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes391[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes392[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes393[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes394[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes395[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes396[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes397[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes398[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes399[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes400[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes401[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes402[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes403[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes404[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes405[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes406[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes407[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes408[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes409[] = {{4, 1, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes410[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes411[] = {{5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes412[] = {{3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes413[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes414[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes415[] = {{4, 3, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes416[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes417[] = {{2, 3, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes418[] = {{2, 3, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes419[] = {{2, 2, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes420[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes421[] = {{1, 1, 1, 1}, {3, 1, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes422[] = {{1, 1, 1, 0}, {4, 3, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes423[] = {{4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes424[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes425[] = {{1, 1, 1, 1}, {2, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes426[] = {{1, 1, 1, 0}, {3, 3, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes427[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes428[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes429[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes430[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes431[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes432[] = {{2, 3, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes433[] = {{2, 3, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes434[] = {{2, 2, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes435[] = {{4, 2, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes436[] = {{1, 1, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes437[] = {{3, 3, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes438[] = {{3, 3, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes439[] = {{1, 1, 1, 0}, {3, 2, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes440[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes441[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes442[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes443[] = {{2, 2, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes444[] = {{3, 2, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes445[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes446[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes447[] = {{1, 1, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes448[] = {{2, 2, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes449[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes450[] = {{2, 2, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes451[] = {{2, 2, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes452[] = {{3, 3, 2, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes453[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes454[] = {{1, 1, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes455[] = {{1, 1, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes456[] = {{3, 3, 2, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes457[] = {{1, 1, 1, 1}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes458[] = {{2, 2, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes459[] = {{3, 3, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes460[] = {{1, 1, 1, 1}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes461[] = {{1, 1, 1, 0}, {4, 3, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes462[] = {{1, 1, 1, 1}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes463[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes464[] = {{2, 1, 1, 0}, {4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes465[] = {{2, 2, 1, 0}, {4, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes466[] = {{1, 1, 1, 0}, {4, 2, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes467[] = {{3, 3, 2, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes468[] = {{1, 1, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes469[] = {{3, 2, 2, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes470[] = {{3, 3, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes471[] = {{1, 1, 1, 0}, {2, 3, 1, 0}, {3, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes472[] = {{2, 3, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes473[] = {{3, 1, 2, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes474[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes475[] = {{1, 1, 1, 1}, {2, 2, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes476[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes477[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes478[] = {{2, 1, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes479[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes480[] = {{2, 3, 1, 0}, {4, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes481[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes482[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes483[] = {{3, 3, 2, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes484[] = {{2, 1, 1, 0}, {5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes485[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes486[] = {{1, 1, 1, 1}, {2, 3, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes487[] = {{2, 2, 1, 0}, {3, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes488[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes489[] = {{1, 1, 1, 1}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes490[] = {{1, 1, 1, 1}, {3, 1, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes491[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes492[] = {{2, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes493[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes494[] = {{3, 1, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes495[] = {{3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes496[] = {{1, 1, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes497[] = {{1, 1, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes498[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes499[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes500[] = {{3, 1, 2, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes501[] = {{1, 1, 1, 1}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes502[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes503[] = {{1, 1, 1, 1}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes504[] = {{2, 1, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes505[] = {{1, 1, 1, 1}, {2, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes506[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes507[] = {{2, 2, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes508[] = {{1, 1, 1, 0}, {4, 1, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes509[] = {{4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes510[] = {{1, 1, 1, 0}, {2, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes511[] = {{1, 1, 1, 1}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes512[] = {{2, 1, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes513[] = {{1, 1, 1, 0}, {2, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes514[] = {{2, 2, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes515[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {3, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes516[] = {{3, 1, 2, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes517[] = {{3, 1, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes518[] = {{1, 1, 1, 1}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes519[] = {{3, 1, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes520[] = {{2, 1, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes521[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes522[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes523[] = {{3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes524[] = {{1, 1, 1, 1}, {2, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes525[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {3, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes526[] = {{4, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes527[] = {{1, 1, 1, 0}, {2, 1, 1, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes528[] = {{3, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes529[] = {{1, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes530[] = {{5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes531[] = {{5, 3, 1, 0}};
const ChordDecodeNote kDecodeNotes532[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes533[] = {{1, 1, 1, 0}, {4, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes534[] = {{3, 1, 2, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes535[] = {{1, 1, 1, 0}, {3, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes536[] = {{4, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes537[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes538[] = {{1, 1, 1, 0}, {2, 2, 1, 0}, {4, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes539[] = {{1, 1, 1, 0}, {5, 2, 2, 0}};
const ChordDecodeNote kDecodeNotes540[] = {{2, 2, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes541[] = {{5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes542[] = {{4, 1, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes543[] = {{2, 3, 1, 0}, {3, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes544[] = {{1, 1, 1, 0}, {3, 1, 1, 0}, {5, 1, 2, 0}};
const ChordDecodeNote kDecodeNotes545[] = {{1, 1, 1, 0}, {4, 1, 2, 0}, {5, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes546[] = {{1, 1, 1, 0}, {3, 3, 2, 0}, {4, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes547[] = {{1, 1, 1, 0}, {3, 1, 2, 0}, {4, 1, 1, 0}};
const ChordDecodeNote kDecodeNotes548[] = {{2, 1, 1, 0}, {5, 3, 2, 0}};
const ChordDecodeNote kDecodeNotes549[] = {{2, 2, 1, 0}, {5, 2, 1, 0}};
const ChordDecodeNote kDecodeNotes550[] = {{2, 3, 1, 0}, {5, 3, 1, 0}};

// 551 entries.
const ChordDecodeEntry kDecodeEntries[] = {
    {" ", kDecodeNotes0, 1},
    {"!", kDecodeNotes1, 1},
    {"#", kDecodeNotes2, 2},
    {"$", kDecodeNotes3, 2},
    {"%", kDecodeNotes4, 1},
    {"&", kDecodeNotes5, 1},
    {"'", kDecodeNotes6, 2},
    {"(", kDecodeNotes7, 1},
    {")", kDecodeNotes8, 2},
    {"*", kDecodeNotes9, 1},
    {"+", kDecodeNotes10, 2},
    {",", kDecodeNotes11, 2},
    {"-", kDecodeNotes12, 2},
    {".", kDecodeNotes13, 1},
    {"/", kDecodeNotes14, 1},
    {"0", kDecodeNotes15, 3},
    {"1", kDecodeNotes16, 3},
    {"2", kDecodeNotes17, 1},
    {"3", kDecodeNotes18, 3},
    {"4", kDecodeNotes19, 1},
    {"5", kDecodeNotes20, 3},
    {"6", kDecodeNotes21, 2},
    {"7", kDecodeNotes22, 2},
    {"8", kDecodeNotes23, 2},
    {"9", kDecodeNotes24, 2},
    {":", kDecodeNotes25, 2},
    {";", kDecodeNotes26, 2},
    {"<", kDecodeNotes27, 2},
    {"=", kDecodeNotes28, 3},
    {">", kDecodeNotes29, 2},
    {"?", kDecodeNotes30, 2},
    {"@", kDecodeNotes31, 2},
    {"A", kDecodeNotes32, 3},
    {"B ", kDecodeNotes33, 2},
    {"B!", kDecodeNotes34, 1},
    {"B#", kDecodeNotes35, 2},
    {"B$", kDecodeNotes36, 2},
    {"B%", kDecodeNotes37, 2},
    {"B&", kDecodeNotes38, 1},
    {"B'", kDecodeNotes39, 2},
    {"B(", kDecodeNotes40, 3},
    {"B) ", kDecodeNotes41, 2},
    {"B)!", kDecodeNotes42, 3},
    {"B)#", kDecodeNotes43, 3},
    {"B)$", kDecodeNotes44, 3},
    {"B)%", kDecodeNotes45, 3},
    {"B)&", kDecodeNotes46, 2},
    {"B)'", kDecodeNotes47, 3},
    {"B)(", kDecodeNotes48, 2},
    {"B))", kDecodeNotes49, 2},
    {"B)*", kDecodeNotes50, 2},
    {"B)+", kDecodeNotes51, 2},
    {"B),", kDecodeNotes52, 2},
    {"B)-", kDecodeNotes53, 3},
    {"B).", kDecodeNotes54, 3},
    {"B)/", kDecodeNotes55, 3},
    {"B)0", kDecodeNotes56, 2},
    {"B)1", kDecodeNotes57, 2},
    {"B)2", kDecodeNotes58, 2},
    {"B)3", kDecodeNotes59, 2},
    {"B)4", kDecodeNotes60, 3},
    {"B)5", kDecodeNotes61, 3},
    {"B)6", kDecodeNotes62, 3},
    {"B)7", kDecodeNotes63, 2},
    {"B)8", kDecodeNotes64, 2},
    {"B)9", kDecodeNotes65, 2},
    {"B):", kDecodeNotes66, 3},
    {"B);", kDecodeNotes67, 3},
    {"B)<", kDecodeNotes68, 3},
    {"B)=", kDecodeNotes69, 3},
    {"B)>", kDecodeNotes70, 2},
    {"B)?", kDecodeNotes71, 2},
    {"B)@", kDecodeNotes72, 2},
    {"B)A", kDecodeNotes73, 3},
    {"B)B", kDecodeNotes74, 3},
    {"B)C", kDecodeNotes75, 3},
    {"B)D", kDecodeNotes76, 3},
    {"B)E", kDecodeNotes77, 2},
    {"B)F", kDecodeNotes78, 2},
    {"B)G", kDecodeNotes79, 2},
    {"B)H", kDecodeNotes80, 2},
    {"B)I", kDecodeNotes81, 3},
    {"B)J", kDecodeNotes82, 3},
    {"B)K", kDecodeNotes83, 3},
    {"B)L", kDecodeNotes84, 3},
    {"B)M", kDecodeNotes85, 2},
    {"B)N", kDecodeNotes86, 2},
    {"B)O", kDecodeNotes87, 2},
    {"B)P", kDecodeNotes88, 2},
    {"B)Q", kDecodeNotes89, 2},
    {"B)R", kDecodeNotes90, 3},
    {"B)S", kDecodeNotes91, 2},
    {"B)T", kDecodeNotes92, 3},
    {"B)U", kDecodeNotes93, 3},
    {"B)V", kDecodeNotes94, 3},
    {"B)W", kDecodeNotes95, 3},
    {"B)X", kDecodeNotes96, 3},
    {"B)Y", kDecodeNotes97, 2},
    {"B)Z", kDecodeNotes98, 2},
    {"B)[", kDecodeNotes99, 2},
    {"B)]", kDecodeNotes100, 2},
    {"B)^", kDecodeNotes101, 2},
    {"B)_", kDecodeNotes102, 2},
    {"B)`", kDecodeNotes103, 2},
    {"B)a", kDecodeNotes104, 3},
    {"B)b", kDecodeNotes105, 3},
    {"B)c", kDecodeNotes106, 3},
    {"B)d", kDecodeNotes107, 3},
    {"B)e", kDecodeNotes108, 3},
    {"B)f", kDecodeNotes109, 3},
    {"B)g", kDecodeNotes110, 3},
    {"B)h", kDecodeNotes111, 3},
    {"B)i", kDecodeNotes112, 3},
    {"B)j", kDecodeNotes113, 3},
    {"B)k", kDecodeNotes114, 3},
    {"B)l", kDecodeNotes115, 2},
    {"B)m", kDecodeNotes116, 2},
    {"B)n", kDecodeNotes117, 2},
    {"B)o", kDecodeNotes118, 2},
    {"B)p", kDecodeNotes119, 2},
    {"B)q", kDecodeNotes120, 2},
    {"B)r", kDecodeNotes121, 2},
    {"B)s", kDecodeNotes122, 2},
    {"B)t", kDecodeNotes123, 2},
    {"B)u", kDecodeNotes124, 2},
    {"B)v", kDecodeNotes125, 2},
    {"B)w", kDecodeNotes126, 2},
    {"B)x", kDecodeNotes127, 2},
    {"B)y", kDecodeNotes128, 2},
    {"B)z", kDecodeNotes129, 2},
    {"B){", kDecodeNotes130, 2},
    {"B)|", kDecodeNotes131, 2},
    {"B)}", kDecodeNotes132, 2},
    {"B)~ ", kDecodeNotes133, 2},
    {"B)~!", kDecodeNotes134, 2},
    {"B)~#", kDecodeNotes135, 2},
    {"B)~$", kDecodeNotes136, 2},
    {"B)~%", kDecodeNotes137, 2},
    {"B)~&", kDecodeNotes138, 2},
    {"B)~'", kDecodeNotes139, 2},
    {"B)~(", kDecodeNotes140, 2},
    {"B)~)", kDecodeNotes141, 2},
    {"B)~*", kDecodeNotes142, 2},
    {"B)~+", kDecodeNotes143, 2},
    {"B)~,", kDecodeNotes144, 2},
    {"B)~-", kDecodeNotes145, 2},
    {"B)~.", kDecodeNotes146, 2},
    {"B)~/", kDecodeNotes147, 2},
    {"B)~0", kDecodeNotes148, 2},
    {"B)~1", kDecodeNotes149, 2},
    {"B)~2", kDecodeNotes150, 2},
    {"B)~3", kDecodeNotes151, 2},
    {"B)~4", kDecodeNotes152, 2},
    {"B)~5", kDecodeNotes153, 2},
    {"B)~6", kDecodeNotes154, 2},
    {"B)~7", kDecodeNotes155, 2},
    {"B)~8", kDecodeNotes156, 2},
    {"B)~9", kDecodeNotes157, 2},
    {"B)~:", kDecodeNotes158, 2},
    {"B)~;", kDecodeNotes159, 2},
    {"B)~<", kDecodeNotes160, 2},
    {"B)~=", kDecodeNotes161, 2},
    {"B)~>", kDecodeNotes162, 2},
    {"B)~?", kDecodeNotes163, 2},
    {"B)~@", kDecodeNotes164, 2},
    {"B)~A", kDecodeNotes165, 2},
    {"B)~B", kDecodeNotes166, 2},
    {"B)~C", kDecodeNotes167, 2},
    {"B)~D", kDecodeNotes168, 2},
    {"B)~E", kDecodeNotes169, 2},
    {"B)~F", kDecodeNotes170, 2},
    {"B)~G", kDecodeNotes171, 2},
    {"B)~H", kDecodeNotes172, 2},
    {"B)~I", kDecodeNotes173, 2},
    {"B)~J", kDecodeNotes174, 2},
    {"B)~K", kDecodeNotes175, 2},
    {"B)~L", kDecodeNotes176, 2},
    {"B)~M", kDecodeNotes177, 2},
    {"B)~N", kDecodeNotes178, 2},
    {"B)~O", kDecodeNotes179, 2},
    {"B)~P", kDecodeNotes180, 2},
    {"B)~Q", kDecodeNotes181, 2},
    {"B)~R", kDecodeNotes182, 2},
    {"B)~S", kDecodeNotes183, 2},
    {"B)~T", kDecodeNotes184, 2},
    {"B)~U", kDecodeNotes185, 2},
    {"B)~V", kDecodeNotes186, 2},
    {"B)~W", kDecodeNotes187, 2},
    {"B)~X", kDecodeNotes188, 2},
    {"B)~Y", kDecodeNotes189, 2},
    {"B)~Z", kDecodeNotes190, 3},
    {"B)~[", kDecodeNotes191, 3},
    {"B)~]", kDecodeNotes192, 3},
    {"B)~^", kDecodeNotes193, 3},
    {"B)~_", kDecodeNotes194, 3},
    {"B)~`", kDecodeNotes195, 3},
    {"B)~a", kDecodeNotes196, 3},
    {"B)~b", kDecodeNotes197, 3},
    {"B)~c", kDecodeNotes198, 3},
    {"B)~d", kDecodeNotes199, 3},
    {"B)~e", kDecodeNotes200, 3},
    {"B)~f", kDecodeNotes201, 3},
    {"B)~g", kDecodeNotes202, 3},
    {"B)~h", kDecodeNotes203, 3},
    {"B)~i", kDecodeNotes204, 3},
    {"B)~j", kDecodeNotes205, 3},
    {"B)~k", kDecodeNotes206, 3},
    {"B)~l", kDecodeNotes207, 3},
    {"B)~m", kDecodeNotes208, 3},
    {"B)~n", kDecodeNotes209, 3},
    {"B)~o", kDecodeNotes210, 3},
    {"B)~p", kDecodeNotes211, 3},
    {"B)~q", kDecodeNotes212, 3},
    {"B)~r", kDecodeNotes213, 3},
    {"B)~s", kDecodeNotes214, 3},
    {"B)~t", kDecodeNotes215, 3},
    {"B)~u", kDecodeNotes216, 3},
    {"B)~v", kDecodeNotes217, 3},
    {"B)~w", kDecodeNotes218, 3},
    {"B)~x", kDecodeNotes219, 3},
    {"B)~y", kDecodeNotes220, 3},
    {"B)~z", kDecodeNotes221, 3},
    {"B)~{", kDecodeNotes222, 3},
    {"B)~|", kDecodeNotes223, 3},
    {"B)~}", kDecodeNotes224, 3},
    {"B)~~ ", kDecodeNotes225, 3},
    {"B)~~!", kDecodeNotes226, 3},
    {"B)~~#", kDecodeNotes227, 3},
    {"B)~~$", kDecodeNotes228, 3},
    {"B)~~%", kDecodeNotes229, 3},
    {"B)~~&", kDecodeNotes230, 3},
    {"B)~~'", kDecodeNotes231, 3},
    {"B)~~(", kDecodeNotes232, 3},
    {"B)~~)", kDecodeNotes233, 3},
    {"B)~~*", kDecodeNotes234, 3},
    {"B)~~+", kDecodeNotes235, 3},
    {"B)~~,", kDecodeNotes236, 3},
    {"B)~~-", kDecodeNotes237, 3},
    {"B)~~.", kDecodeNotes238, 3},
    {"B)~~/", kDecodeNotes239, 3},
    {"B)~~0", kDecodeNotes240, 3},
    {"B)~~1", kDecodeNotes241, 3},
    {"B)~~2", kDecodeNotes242, 3},
    {"B)~~3", kDecodeNotes243, 3},
    {"B)~~4", kDecodeNotes244, 3},
    {"B)~~5", kDecodeNotes245, 3},
    {"B)~~6", kDecodeNotes246, 3},
    {"B)~~7", kDecodeNotes247, 3},
    {"B)~~8", kDecodeNotes248, 3},
    {"B)~~9", kDecodeNotes249, 3},
    {"B)~~:", kDecodeNotes250, 3},
    {"B)~~;", kDecodeNotes251, 3},
    {"B)~~<", kDecodeNotes252, 3},
    {"B)~~=", kDecodeNotes253, 3},
    {"B)~~>", kDecodeNotes254, 3},
    {"B)~~?", kDecodeNotes255, 3},
    {"B)~~@", kDecodeNotes256, 3},
    {"B)~~A", kDecodeNotes257, 3},
    {"B)~~B", kDecodeNotes258, 3},
    {"B)~~C", kDecodeNotes259, 3},
    {"B)~~D", kDecodeNotes260, 3},
    {"B)~~E", kDecodeNotes261, 3},
    {"B)~~F", kDecodeNotes262, 3},
    {"B)~~G", kDecodeNotes263, 3},
    {"B)~~H", kDecodeNotes264, 3},
    {"B)~~I", kDecodeNotes265, 3},
    {"B)~~J", kDecodeNotes266, 3},
    {"B)~~K", kDecodeNotes267, 3},
    {"B)~~L", kDecodeNotes268, 3},
    {"B)~~M", kDecodeNotes269, 3},
    {"B)~~N", kDecodeNotes270, 3},
    {"B)~~O", kDecodeNotes271, 3},
    {"B)~~P", kDecodeNotes272, 3},
    {"B)~~Q", kDecodeNotes273, 3},
    {"B)~~R", kDecodeNotes274, 3},
    {"B)~~S", kDecodeNotes275, 3},
    {"B)~~T", kDecodeNotes276, 3},
    {"B)~~U", kDecodeNotes277, 3},
    {"B)~~V", kDecodeNotes278, 3},
    {"B)~~W", kDecodeNotes279, 3},
    {"B)~~X", kDecodeNotes280, 3},
    {"B)~~Y", kDecodeNotes281, 3},
    {"B)~~Z", kDecodeNotes282, 3},
    {"B)~~[", kDecodeNotes283, 3},
    {"B)~~]", kDecodeNotes284, 3},
    {"B)~~^", kDecodeNotes285, 3},
    {"B)~~_", kDecodeNotes286, 3},
    {"B)~~`", kDecodeNotes287, 3},
    {"B)~~a", kDecodeNotes288, 3},
    {"B)~~b", kDecodeNotes289, 3},
    {"B)~~c", kDecodeNotes290, 3},
    {"B)~~d", kDecodeNotes291, 3},
    {"B)~~e", kDecodeNotes292, 3},
    {"B)~~f", kDecodeNotes293, 3},
    {"B)~~g", kDecodeNotes294, 3},
    {"B)~~h", kDecodeNotes295, 3},
    {"B)~~i", kDecodeNotes296, 3},
    {"B)~~j", kDecodeNotes297, 3},
    {"B)~~k", kDecodeNotes298, 3},
    {"B)~~l", kDecodeNotes299, 3},
    {"B)~~m", kDecodeNotes300, 3},
    {"B)~~n", kDecodeNotes301, 3},
    {"B)~~o", kDecodeNotes302, 3},
    {"B)~~p", kDecodeNotes303, 3},
    {"B)~~q", kDecodeNotes304, 3},
    {"B)~~r", kDecodeNotes305, 3},
    {"B)~~s", kDecodeNotes306, 3},
    {"B)~~t", kDecodeNotes307, 3},
    {"B)~~u", kDecodeNotes308, 3},
    {"B)~~v", kDecodeNotes309, 3},
    {"B)~~w", kDecodeNotes310, 3},
    {"B)~~x", kDecodeNotes311, 3},
    {"B)~~y", kDecodeNotes312, 3},
    {"B)~~z", kDecodeNotes313, 3},
    {"B)~~{", kDecodeNotes314, 3},
    {"B)~~|", kDecodeNotes315, 3},
    {"B)~~}", kDecodeNotes316, 3},
    {"B)~~~ ", kDecodeNotes317, 3},
    {"B)~~~!", kDecodeNotes318, 3},
    {"B)~~~#", kDecodeNotes319, 3},
    {"B)~~~$", kDecodeNotes320, 3},
    {"B)~~~%", kDecodeNotes321, 3},
    {"B)~~~&", kDecodeNotes322, 3},
    {"B)~~~'", kDecodeNotes323, 3},
    {"B)~~~(", kDecodeNotes324, 3},
    {"B)~~~)", kDecodeNotes325, 3},
    {"B)~~~*", kDecodeNotes326, 3},
    {"B)~~~+", kDecodeNotes327, 3},
    {"B)~~~,", kDecodeNotes328, 3},
    {"B)~~~-", kDecodeNotes329, 3},
    {"B)~~~.", kDecodeNotes330, 3},
    {"B)~~~/", kDecodeNotes331, 3},
    {"B)~~~0", kDecodeNotes332, 3},
    {"B)~~~1", kDecodeNotes333, 3},
    {"B)~~~2", kDecodeNotes334, 3},
    {"B)~~~3", kDecodeNotes335, 3},
    {"B)~~~4", kDecodeNotes336, 3},
    {"B)~~~5", kDecodeNotes337, 3},
    {"B)~~~6", kDecodeNotes338, 3},
    {"B)~~~7", kDecodeNotes339, 3},
    {"B)~~~8", kDecodeNotes340, 3},
    {"B)~~~9", kDecodeNotes341, 3},
    {"B)~~~:", kDecodeNotes342, 3},
    {"B)~~~;", kDecodeNotes343, 3},
    {"B)~~~<", kDecodeNotes344, 3},
    {"B)~~~=", kDecodeNotes345, 3},
    {"B)~~~>", kDecodeNotes346, 3},
    {"B)~~~?", kDecodeNotes347, 3},
    {"B)~~~@", kDecodeNotes348, 3},
    {"B)~~~A", kDecodeNotes349, 3},
    {"B)~~~B", kDecodeNotes350, 3},
    {"B)~~~C", kDecodeNotes351, 3},
    {"B)~~~D", kDecodeNotes352, 3},
    {"B)~~~E", kDecodeNotes353, 3},
    {"B)~~~F", kDecodeNotes354, 3},
    {"B)~~~G", kDecodeNotes355, 3},
    {"B)~~~H", kDecodeNotes356, 3},
    {"B)~~~I", kDecodeNotes357, 3},
    {"B)~~~J", kDecodeNotes358, 3},
    {"B)~~~K", kDecodeNotes359, 3},
    {"B)~~~L", kDecodeNotes360, 3},
    {"B)~~~M", kDecodeNotes361, 3},
    {"B)~~~N", kDecodeNotes362, 3},
    {"B)~~~O", kDecodeNotes363, 3},
    {"B)~~~P", kDecodeNotes364, 3},
    {"B)~~~Q", kDecodeNotes365, 3},
    {"B)~~~R", kDecodeNotes366, 3},
    {"B)~~~S", kDecodeNotes367, 3},
    {"B)~~~T", kDecodeNotes368, 3},
    {"B)~~~U", kDecodeNotes369, 3},
    {"B)~~~V", kDecodeNotes370, 3},
    {"B)~~~W", kDecodeNotes371, 3},
    {"B)~~~X", kDecodeNotes372, 3},
    {"B)~~~Y", kDecodeNotes373, 3},
    {"B)~~~Z", kDecodeNotes374, 3},
    {"B)~~~[", kDecodeNotes375, 3},
    {"B)~~~]", kDecodeNotes376, 3},
    {"B)~~~^", kDecodeNotes377, 3},
    {"B)~~~_", kDecodeNotes378, 3},
    {"B)~~~`", kDecodeNotes379, 3},
    {"B)~~~a", kDecodeNotes380, 3},
    {"B)~~~b", kDecodeNotes381, 3},
    {"B)~~~c", kDecodeNotes382, 3},
    {"B)~~~d", kDecodeNotes383, 3},
    {"B)~~~e", kDecodeNotes384, 3},
    {"B)~~~f", kDecodeNotes385, 3},
    {"B)~~~g", kDecodeNotes386, 3},
    {"B)~~~h", kDecodeNotes387, 3},
    {"B)~~~i", kDecodeNotes388, 3},
    {"B)~~~j", kDecodeNotes389, 3},
    {"B)~~~k", kDecodeNotes390, 3},
    {"B)~~~l", kDecodeNotes391, 3},
    {"B)~~~m", kDecodeNotes392, 3},
    {"B)~~~n", kDecodeNotes393, 3},
    {"B)~~~o", kDecodeNotes394, 3},
    {"B)~~~p", kDecodeNotes395, 3},
    {"B)~~~q", kDecodeNotes396, 3},
    {"B)~~~r", kDecodeNotes397, 3},
    {"B)~~~s", kDecodeNotes398, 3},
    {"B)~~~t", kDecodeNotes399, 3},
    {"B)~~~u", kDecodeNotes400, 3},
    {"B)~~~v", kDecodeNotes401, 3},
    {"B)~~~w", kDecodeNotes402, 3},
    {"B)~~~x", kDecodeNotes403, 3},
    {"B)~~~y", kDecodeNotes404, 3},
    {"B)~~~z", kDecodeNotes405, 3},
    {"B)~~~{", kDecodeNotes406, 3},
    {"B)~~~|", kDecodeNotes407, 3},
    {"B*", kDecodeNotes408, 3},
    {"B+", kDecodeNotes409, 2},
    {"B,", kDecodeNotes410, 3},
    {"B-", kDecodeNotes411, 1},
    {"B.", kDecodeNotes412, 1},
    {"B/", kDecodeNotes413, 3},
    {"B0", kDecodeNotes414, 3},
    {"B1", kDecodeNotes415, 2},
    {"B2", kDecodeNotes416, 3},
    {"B3", kDecodeNotes417, 2},
    {"B4", kDecodeNotes418, 2},
    {"B5", kDecodeNotes419, 2},
    {"B6", kDecodeNotes420, 3},
    {"B7", kDecodeNotes421, 3},
    {"B8", kDecodeNotes422, 3},
    {"B9", kDecodeNotes423, 1},
    {"B:", kDecodeNotes424, 3},
    {"B;", kDecodeNotes425, 2},
    {"B<", kDecodeNotes426, 3},
    {"B=", kDecodeNotes427, 3},
    {"B>", kDecodeNotes428, 3},
    {"B?", kDecodeNotes429, 3},
    {"B@", kDecodeNotes430, 3},
    {"BA", kDecodeNotes431, 3},
    {"BB", kDecodeNotes432, 2},
    {"BC", kDecodeNotes433, 2},
    {"BD", kDecodeNotes434, 2},
    {"BE", kDecodeNotes435, 2},
    {"BF", kDecodeNotes436, 2},
    {"BG", kDecodeNotes437, 2},
    {"BH", kDecodeNotes438, 2},
    {"BI", kDecodeNotes439, 3},
    {"BJ", kDecodeNotes440, 3},
    {"BK", kDecodeNotes441, 3},
    {"BL", kDecodeNotes442, 3},
    {"BM", kDecodeNotes443, 2},
    {"BN", kDecodeNotes444, 2},
    {"BO", kDecodeNotes445, 3},
    {"BP", kDecodeNotes446, 3},
    {"BQ", kDecodeNotes447, 2},
    {"BR", kDecodeNotes448, 2},
    {"BS", kDecodeNotes449, 3},
    {"BT", kDecodeNotes450, 2},
    {"BU", kDecodeNotes451, 2},
    {"BV", kDecodeNotes452, 2},
    {"BW", kDecodeNotes453, 3},
    {"BX", kDecodeNotes454, 2},
    {"BY", kDecodeNotes455, 2},
    {"BZ", kDecodeNotes456, 2},
    {"B[", kDecodeNotes457, 2},
    {"B]", kDecodeNotes458, 2},
    {"B^", kDecodeNotes459, 2},
    {"B_", kDecodeNotes460, 2},
    {"B`", kDecodeNotes461, 3},
    {"Ba", kDecodeNotes462, 2},
    {"Bb", kDecodeNotes463, 3},
    {"Bc", kDecodeNotes464, 2},
    {"Bd", kDecodeNotes465, 2},
    {"Be", kDecodeNotes466, 3},
    {"Bf", kDecodeNotes467, 2},
    {"Bg", kDecodeNotes468, 2},
    {"Bh", kDecodeNotes469, 2},
    {"Bi", kDecodeNotes470, 2},
    {"Bj", kDecodeNotes471, 3},
    {"Bk", kDecodeNotes472, 2},
    {"Bl", kDecodeNotes473, 2},
    {"Bm", kDecodeNotes474, 3},
    {"Bn", kDecodeNotes475, 3},
    {"Bo", kDecodeNotes476, 3},
    {"Bp", kDecodeNotes477, 3},
    {"Bq", kDecodeNotes478, 2},
    {"Br", kDecodeNotes479, 3},
    {"Bs", kDecodeNotes480, 2},
    {"Bt", kDecodeNotes481, 3},
    {"Bu", kDecodeNotes482, 3},
    {"Bv", kDecodeNotes483, 2},
    {"Bw", kDecodeNotes484, 2},
    {"Bx", kDecodeNotes485, 3},
    {"By", kDecodeNotes486, 3},
    {"Bz", kDecodeNotes487, 2},
    {"B{", kDecodeNotes488, 3},
    {"B|", kDecodeNotes489, 2},
    {"B}", kDecodeNotes490, 3},
    {"B~", kDecodeNotes491, 3},
    {"C", kDecodeNotes492, 1},
    {"D", kDecodeNotes493, 3},
    {"E", kDecodeNotes494, 2},
    {"F", kDecodeNotes495, 1},
    {"G", kDecodeNotes496, 2},
    {"H", kDecodeNotes497, 2},
    {"I", kDecodeNotes498, 3},
    {"J", kDecodeNotes499, 3},
    {"K", kDecodeNotes500, 2},
    {"L", kDecodeNotes501, 2},
    {"M", kDecodeNotes502, 3},
    {"N", kDecodeNotes503, 2},
    {"O", kDecodeNotes504, 2},
    {"P", kDecodeNotes505, 3},
    {"Q", kDecodeNotes506, 3},
    {"R", kDecodeNotes507, 2},
    {"S", kDecodeNotes508, 3},
    {"T", kDecodeNotes509, 1},
    {"U", kDecodeNotes510, 2},
    {"V", kDecodeNotes511, 2},
    {"W", kDecodeNotes512, 2},
    {"X", kDecodeNotes513, 2},
    {"Y", kDecodeNotes514, 2},
    {"Z", kDecodeNotes515, 3},
    {"[", kDecodeNotes516, 2},
    {"]", kDecodeNotes517, 2},
    {"^", kDecodeNotes518, 2},
    {"_", kDecodeNotes519, 2},
    {"`", kDecodeNotes520, 2},
    {"a", kDecodeNotes521, 3},
    {"b", kDecodeNotes522, 3},
    {"c", kDecodeNotes523, 1},
    {"d", kDecodeNotes524, 2},
    {"e", kDecodeNotes525, 3},
    {"f", kDecodeNotes526, 2},
    {"g", kDecodeNotes527, 3},
    {"h", kDecodeNotes528, 2},
    {"i", kDecodeNotes529, 2},
    {"j", kDecodeNotes530, 1},
    {"k", kDecodeNotes531, 1},
    {"l", kDecodeNotes532, 3},
    {"m", kDecodeNotes533, 3},
    {"n", kDecodeNotes534, 2},
    {"o", kDecodeNotes535, 2},
    {"p", kDecodeNotes536, 1},
    {"q", kDecodeNotes537, 3},
    {"r", kDecodeNotes538, 3},
    {"s", kDecodeNotes539, 2},
    {"t", kDecodeNotes540, 2},
    {"u", kDecodeNotes541, 1},
    {"v", kDecodeNotes542, 2},
    {"w", kDecodeNotes543, 2},
    {"x", kDecodeNotes544, 3},
    {"y", kDecodeNotes545, 3},
    {"z", kDecodeNotes546, 3},
    {"{", kDecodeNotes547, 3},
    {"|", kDecodeNotes548, 2},
    {"}", kDecodeNotes549, 2},
    {"~", kDecodeNotes550, 2},
};

}  // namespace

const std::unordered_map<int64_t, std::string>& chord_encode() {
    static const std::unordered_map<int64_t, std::string> table = [] {
        std::unordered_map<int64_t, std::string> m;
        m.reserve(sizeof(kEntries) / sizeof(kEntries[0]) * 2);
        for (const auto& e : kEntries)
            m.emplace(e.hash, e.code);
        return m;
    }();
    return table;
}

const std::string* encode_chord(int64_t hash) {
    const auto& m = chord_encode();
    auto it = m.find(hash);
    return it == m.end() ? nullptr : &it->second;
}

const std::unordered_map<std::string, std::vector<ChordNoteFields>>&
chord_decode() {
    static const std::unordered_map<std::string,
                                    std::vector<ChordNoteFields>>
        table = [] {
            std::unordered_map<std::string, std::vector<ChordNoteFields>> m;
            m.reserve(sizeof(kDecodeEntries) / sizeof(kDecodeEntries[0]) * 2);
            for (const auto& e : kDecodeEntries) {
                std::vector<ChordNoteFields> notes;
                notes.reserve(e.count);
                for (int i = 0; i < e.count; ++i)
                    notes.push_back({e.notes[i].color, e.notes[i].dyn,
                                     e.notes[i].cym, e.notes[i].is2x});
                m.emplace(e.code, std::move(notes));
            }
            return m;
        }();
    return table;
}

const std::vector<ChordNoteFields>* decode_chord(const std::string& code) {
    const auto& m = chord_decode();
    auto it = m.find(code);
    return it == m.end() ? nullptr : &it->second;
}

}  // namespace hydra
