"""Code-generate src/core/chord_tables.cpp from hydra.hyencode.CHORD_ENCODE.

The chord encode table (chord hash -> display string) is a large hand-built
lookup in hyencode.py. Rather than retype ~550 entries into C++ by hand, this
emits them mechanically from the Python source, so the two can never drift.

    .venv\\Scripts\\python.exe tools\\gen_chord_tables.py

Idempotent: re-running with no change to hyencode produces a byte-identical
file. tests/test_chord_tables.cpp additionally checks the generated table
against golden/chord_encode.json.
"""

import os
import pathlib
import sys

os.environ["HYDRA_NO_NATIVE"] = "1"

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))

import hydra.hyencode as hyencode  # noqa: E402

OUT = ROOT / "src" / "core" / "chord_tables.cpp"

INT64_MIN = -(2 ** 63)
INT64_MAX = 2 ** 63 - 1


def cpp_string(s):
    """Escape a Python str as a C++ narrow string literal body.

    The encode values are all printable ASCII, but they include characters
    that must be escaped in a literal (backslash, double quote).
    """
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= o <= 0x7E:
            out.append(ch)
        else:
            # Not expected in this table; emit a safe hex escape if it ever is.
            out.append(f"\\x{o:02x}")
    return "".join(out)


def cpp_int64(n):
    """Render a Python int as a C++ int64 literal.

    INT64_MIN cannot be written as a negative literal (the value -9223372...
    is parsed as unary minus applied to a too-large positive literal), so it
    is emitted via the standard INT64_MIN idiom.
    """
    if not (INT64_MIN <= n <= INT64_MAX):
        raise ValueError(f"chord hash out of int64 range: {n}")
    if n == INT64_MIN:
        return "(-9223372036854775807LL - 1)"
    return f"{n}LL"


def main():
    items = sorted(hyencode.CHORD_ENCODE.items(), key=lambda kv: kv[0])
    decode_items = sorted(hyencode.CHORD_DECODE.items(), key=lambda kv: kv[0])

    lines = []
    lines.append("// GENERATED by tools/gen_chord_tables.py from")
    lines.append("// hydra/hyencode.py:CHORD_ENCODE / CHORD_DECODE. Do not edit by")
    lines.append("// hand; re-run the generator instead.")
    lines.append("//")
    lines.append("// Chord hash -> display string, the reverse of what the")
    lines.append("// scoring code hashes a chord to, plus the display-string ->")
    lines.append("// note-field list needed by Chord::from_code.")
    lines.append("")
    lines.append('#include "core/chord_tables.h"')
    lines.append("")
    lines.append("namespace hydra {")
    lines.append("namespace {")
    lines.append("")
    lines.append("struct ChordEncodeEntry {")
    lines.append("    int64_t hash;")
    lines.append("    const char* code;")
    lines.append("};")
    lines.append("")
    lines.append(f"// {len(items)} entries.")
    lines.append("const ChordEncodeEntry kEntries[] = {")
    for h, s in items:
        lines.append(f'    {{{cpp_int64(h)}, "{cpp_string(s)}"}},')
    lines.append("};")
    lines.append("")
    lines.append("struct ChordDecodeNote {")
    lines.append("    int color;")
    lines.append("    int dyn;")
    lines.append("    int cym;")
    lines.append("    int is2x;")
    lines.append("};")
    lines.append("struct ChordDecodeEntry {")
    lines.append("    const char* code;")
    lines.append("    const ChordDecodeNote* notes;")
    lines.append("    int count;")
    lines.append("};")
    lines.append("")
    # Each chord's note list is emitted as its own small static array, then
    # referenced by the decode entry, so the whole table stays a flat literal.
    for idx, (code, notes) in enumerate(decode_items):
        parts = []
        for n in notes:
            parts.append(
                f"{{{int(n['color'])}, {int(n['dyn'])}, "
                f"{int(n['cym'])}, {1 if n['2x'] else 0}}}"
            )
        lines.append(
            f"const ChordDecodeNote kDecodeNotes{idx}[] = {{{', '.join(parts)}}};"
        )
    lines.append("")
    lines.append(f"// {len(decode_items)} entries.")
    lines.append("const ChordDecodeEntry kDecodeEntries[] = {")
    for idx, (code, notes) in enumerate(decode_items):
        lines.append(
            f'    {{"{cpp_string(code)}", kDecodeNotes{idx}, {len(notes)}}},'
        )
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace")
    lines.append("")
    lines.append("const std::unordered_map<int64_t, std::string>& chord_encode() {")
    lines.append("    static const std::unordered_map<int64_t, std::string> table = [] {")
    lines.append("        std::unordered_map<int64_t, std::string> m;")
    lines.append("        m.reserve(sizeof(kEntries) / sizeof(kEntries[0]) * 2);")
    lines.append("        for (const auto& e : kEntries)")
    lines.append("            m.emplace(e.hash, e.code);")
    lines.append("        return m;")
    lines.append("    }();")
    lines.append("    return table;")
    lines.append("}")
    lines.append("")
    lines.append("const std::string* encode_chord(int64_t hash) {")
    lines.append("    const auto& m = chord_encode();")
    lines.append("    auto it = m.find(hash);")
    lines.append("    return it == m.end() ? nullptr : &it->second;")
    lines.append("}")
    lines.append("")
    lines.append("const std::unordered_map<std::string, std::vector<ChordNoteFields>>&")
    lines.append("chord_decode() {")
    lines.append("    static const std::unordered_map<std::string,")
    lines.append("                                    std::vector<ChordNoteFields>>")
    lines.append("        table = [] {")
    lines.append("            std::unordered_map<std::string, std::vector<ChordNoteFields>> m;")
    lines.append("            m.reserve(sizeof(kDecodeEntries) / sizeof(kDecodeEntries[0]) * 2);")
    lines.append("            for (const auto& e : kDecodeEntries) {")
    lines.append("                std::vector<ChordNoteFields> notes;")
    lines.append("                notes.reserve(e.count);")
    lines.append("                for (int i = 0; i < e.count; ++i)")
    lines.append("                    notes.push_back({e.notes[i].color, e.notes[i].dyn,")
    lines.append("                                     e.notes[i].cym, e.notes[i].is2x});")
    lines.append("                m.emplace(e.code, std::move(notes));")
    lines.append("            }")
    lines.append("            return m;")
    lines.append("        }();")
    lines.append("    return table;")
    lines.append("}")
    lines.append("")
    lines.append("const std::vector<ChordNoteFields>* decode_chord(const std::string& code) {")
    lines.append("    const auto& m = chord_decode();")
    lines.append("    auto it = m.find(code);")
    lines.append("    return it == m.end() ? nullptr : &it->second;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace hydra")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(items)} encode, {len(decode_items)} decode entries)")


if __name__ == "__main__":
    main()
